const products = [
  {
    id: "1",
    name: "Wireless Mouse",
    image: "https://example.com/images/wireless-mouse.jpg",
    description: "A sleek wireless mouse with ergonomic design.",
    price: 29.99,
    quantity: 150,
    onstock: true,
    category: "101",
  },
  {
    id: "2",
    name: "Gaming Keyboard",
    image: "https://example.com/images/gaming-keyboard.jpg",
    description: "A RGB mechanical gaming keyboard with customizable keys.",
    price: 79.99,
    quantity: 75,
    onstock: true,
    category: "101",
  },
  {
    id: "3",
    name: "HD Monitor",
    image: "https://example.com/images/hd-monitor.jpg",
    description: "24-inch Full HD monitor with vibrant colors.",
    price: 129.99,
    quantity: 50,
    onstock: true,
    category: "102",
  },
  {
    id: "4",
    name: "Portable SSD",
    image: "https://example.com/images/portable-ssd.jpg",
    description: "1TB portable SSD with lightning-fast data transfer.",
    price: 99.99,
    quantity: 200,
    onstock: true,
    category: "103",
  },
  {
    id: "5",
    name: "Noise-Canceling Headphones",
    image: "https://example.com/images/noise-canceling-headphones.jpg",
    description: "Premium over-ear headphones with active noise canceling.",
    price: 199.99,
    quantity: 35,
    onstock: true,
    category: "104",
  },
  {
    id: "6",
    name: "Smartphone Stand",
    image: "https://example.com/images/smartphone-stand.jpg",
    description: "Adjustable and durable smartphone stand.",
    price: 15.99,
    quantity: 300,
    onstock: true,
    category: "105",
  },
  {
    id: "7",
    name: "Wireless Charger",
    image: "https://example.com/images/wireless-charger.jpg",
    description: "Fast wireless charger compatible with multiple devices.",
    price: 39.99,
    quantity: 120,
    onstock: true,
    category: "106",
  },
  {
    id: "8",
    name: "USB-C Cable",
    image: "https://example.com/images/usb-c-cable.jpg",
    description: "Durable and fast USB-C charging and data cable.",
    price: 9.99,
    quantity: 500,
    onstock: true,
    category: "107",
  },
  {
    id: "9",
    name: "Laptop Backpack",
    image: "https://example.com/images/laptop-backpack.jpg",
    description: "Waterproof and spacious laptop backpack.",
    price: 59.99,
    quantity: 85,
    onstock: true,
    category: "108",
  },
  {
    id: "10",
    name: "Bluetooth Speaker",
    image: "https://example.com/images/bluetooth-speaker.jpg",
    description: "Portable Bluetooth speaker with powerful sound.",
    price: 49.99,
    quantity: 95,
    onstock: true,
    category: "109",
  },
];

export const db = {
  products
}
